# Generated by Django 4.1.3 on 2022-11-22 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_recipe_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('rating', models.CharField(choices=[('EX', 'Excellent!'), ('YM', 'Yummy!'), ('AL', 'Alright.'), ('MH', 'Meh...'), ('DS', 'Disgusting.')], default='EX', max_length=2)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
    ]
