# Generated by Django 4.1.3 on 2022-11-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
