# Generated by Django 4.1.3 on 2022-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('EX', 'Excellent!'), ('YM', 'Yummy!'), ('AL', 'Alright.'), ('MH', 'Meh...'), ('DS', 'Disgusting.')], default='EX', max_length=16),
        ),
    ]
