# Generated by Django 4.1.3 on 2022-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='region',
            field=models.CharField(choices=[('NORTH AMERICAN', 'North America'), ('SOUTH AMERICAN', 'South America'), ('CENTRAL AMERICAN', 'Central America'), ('EUROPEAN', 'Europe'), ('ASIAN', 'Asia'), ('MIDDLE EASTERN', 'Middle East'), ('AFRICAN', 'Africa'), ('OCEANIC', 'Oceania')], default='NORTH AMERICAN', max_length=16),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('EX', 'Excellent!'), ('YM', 'Yummy!'), ('AL', 'Alright.'), ('MH', 'Meh...'), ('DS', 'Disgusting.')], default='EX', max_length=2),
        ),
    ]
