# Generated by Django 4.1.3 on 2022-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_recipe_region_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('CA', 'Central America'), ('EU', 'Europe'), ('AS', 'Asia'), ('ME', 'Middle East'), ('AF', 'Africa'), ('OC', 'Oceania')], default='NA', max_length=2),
        ),
    ]
